name: ems_webview
description: EMS Dien Luc WebView App with ESC/POS Bluetooth Printing support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Using latest flutter_inappwebview
  flutter_inappwebview: ^6.1.5
  esc_pos_bluetooth: ^0.4.1
  flutter_bluetooth_basic: any
  esc_pos_utils: ^1.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  image: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  flutter_bluetooth_basic:
    path: ./flutter_bluetooth_basic_local
